name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 * * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Check if image exists
      run: |
        cargo run
        if (Test-Path -Path iss_map.png -PathType Leaf) {echo "Exists"} else {exit 1}
